FROM golang:1.21.0 as builder

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY . .
RUN go mod download && go mod verify

RUN go build -v -o /usr/local/bin/app ./...
EXPOSE 8080
ENTRYPOINT ["app"]