name: Deploy to AWS

on:
  workflow_call:
    inputs:
      workspace:
        description: 'Workspace path. What application to deply.'
        required: true
        type: string
      version:
        description: 'Version to use in system'
        required: false
        type: string  
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy ${{inputs.workspace}}
    runs-on: ubuntu-latest
    
